"""Back to original database

Revision ID: 052bd70f873f
Revises: 74ee3d875fe5
Create Date: 2020-11-17 17:04:32.401558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052bd70f873f'
down_revision = '74ee3d875fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favourite_colour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favourite_colour', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
